# Site title and subtitle. This is used in _includes/header.html
title: 'Podlove'
subtitle: 'Podlove Personal Media Development'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'http://github.com/podlove'

# projects:
#     podlove-publisher:
#         title: 'Podlove Publisher'
#     podlove-web-player:
#         title: 'Podlove Web Player'
#     podlove-subscribe-button:
#         title: 'Podlove Subscribe Button'

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: /:categories/:title

# Syntax highlighting
highlighter: 'pygments'

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

gems:
  - jekyll-redirect-from

playerPath: '/bower_components/podlove-web-player/dist'
